import { Bell, Moon, Sun, UserRound } from "lucide-react"
import { useState } from "react"
import ConfirmDialog from "../components/ConfirmDialog"
import { useStudy } from "../context/useStudy"
import { useAuth } from "../context/useAuth"

export default function Settings() {
  const { theme, setTheme, clearTasks } = useStudy()
  const { user } = useAuth()
  const [notifications, setNotifications] = useState(true)
  const [confirming, setConfirming] = useState(false)
  return <div className="max-w-3xl space-y-7"><section><p className="eyebrow">Workspace preferences</p><h1 className="page-title">Settings</h1><p className="page-subtitle">Make Study Flow feel like your own focused workspace.</p></section><section className="panel"><div className="settings-row"><div className="settings-icon"><UserRound size={19} /></div><div className="min-w-0 flex-1"><h2 className="font-semibold text-slate-900 dark:text-white">Profile</h2><p className="mt-1 text-sm text-slate-500">Your personal dashboard identity</p><p className="mt-2 text-sm font-medium text-slate-800 dark:text-slate-200">{user.name}</p><p className="text-xs text-slate-400">{user.email}</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-sm font-semibold text-indigo-600 dark:bg-indigo-500/10">Active</span></div></section><section className="panel divide-y divide-slate-100 dark:divide-slate-800"><div className="settings-row"><div className="settings-icon"><Sun size={19} /></div><div className="min-w-0 flex-1"><h2 className="font-semibold text-slate-900 dark:text-white">Theme preference</h2><p className="mt-1 text-sm text-slate-500">Choose the appearance that helps you focus</p></div><div className="flex rounded-xl bg-slate-100 p-1 dark:bg-slate-800"><button onClick={() => setTheme("light")} className={`theme-choice ${theme === "light" ? "theme-choice-active" : ""}`}><Sun size={15} /> Light</button><button onClick={() => setTheme("dark")} className={`theme-choice ${theme === "dark" ? "theme-choice-active" : ""}`}><Moon size={15} /> Dark</button></div></div><div className="settings-row"><div className="settings-icon"><Bell size={19} /></div><div className="min-w-0 flex-1"><h2 className="font-semibold text-slate-900 dark:text-white">Notifications</h2><p className="mt-1 text-sm text-slate-500">Receive gentle reminders about your study plan</p></div><button onClick={() => setNotifications((current) => !current)} className={`toggle ${notifications ? "toggle-on" : ""}`} aria-label="Toggle notifications"><span /></button></div></section><section className="panel border-rose-100 dark:border-rose-500/20"><h2 className="font-semibold text-slate-900 dark:text-white">Clear all tasks</h2><p className="mt-1 text-sm text-slate-500">Remove every task from your workspace. This cannot be undone.</p><button disabled={false} onClick={() => setConfirming(true)} className="button-danger mt-5">Clear all tasks</button></section>{confirming && <ConfirmDialog title="Clear all tasks?" message="Are you sure you want to delete every task? This action cannot be undone." confirmLabel="Clear all" onCancel={() => setConfirming(false)} onConfirm={() => { clearTasks(); setConfirming(false) }} />}</div>
}
